#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Quick scanner for /dev/input events to discover keycodes generated by
Adafruit Mini PiTFT (gpio-keys) or other button devices.

Usage (in your venv):
  python evdev_scan.py

If permission denied, either run with sudo (temporary) or add your user to
'input' group and re-login:
  sudo usermod -aG input $USER
  # log out/in

Press your TFT's top/bottom buttons and watch the printed keycodes.
Then map them in your app (TOP/BOTTOM) accordingly.
"""

import select
from evdev import InputDevice, categorize, ecodes, list_devices

paths = list_devices()
if not paths:
    print('[SCAN] No /dev/input/event* devices found. Are you on a Pi with gpio-keys overlay?')
    print('[SCAN] Try: sudo apt install python3-evdev  (and)  pip install evdev')
    raise SystemExit(1)

print('[SCAN] Devices:')
for p in paths:
    try:
        dev = InputDevice(p)
        print('  ', p, '  name="%s"  phys="%s"' % (dev.name, dev.phys))
    except Exception as e:
        print('  ', p, '  (open failed:', e, ')')

# Open all readable devices
devices = []
for p in paths:
    try:
        devices.append(InputDevice(p))
    except Exception:
        pass

fd_to_dev = {dev.fd: dev for dev in devices}
print('\n[SCAN] Listening. Press TFT buttons (Ctrl+C to stop)')

try:
    while True:
        r, _, _ = select.select(fd_to_dev.keys(), [], [])
        for fd in r:
            dev = fd_to_dev[fd]
            for event in dev.read():
                if event.type == ecodes.EV_KEY:
                    ke = categorize(event)
                    # event.value: 1=key down, 0=key up, 2=hold
                    if event.value == 1:  # on key down
                        name = ke.keycode
                        if isinstance(name, (list, tuple)):
                            name = '+'.join(name)
                        print('[KEY]', dev.path, 'name="%s"' % dev.name, 'keycode=', name, 'code=', event.code)
except KeyboardInterrupt:
    print('\n[SCAN] Stopped')
